[package]
name = "rumtk-web-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4.13"

[dependencies.rumtk-web]
path = ".."

[dependencies.rumtk-core]
path = "../../rumtk-core"

[[bin]]
name = "fuzz_api"
path = "fuzz_targets/fuzz_api.rs"
test = false
doc = false
bench = false
